# Generated by Django 5.2.7 on 2025-10-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_name',
            new_name='unique_name',
        ),
        migrations.AlterField(
            model_name='file',
            name='coment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.URLField(blank=True, max_length=255, unique=True),
        ),
    ]
