# Generated by Django 5.2.7 on 2025-10-29 07:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='file',
            name='public_url_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
