# Generated by Django 5.2.7 on 2025-10-07 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_rename_file_name_file_unique_name_alter_file_coment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='coment',
            new_name='comment',
        ),
    ]
