# Generated by Django 5.2.7 on 2025-10-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_rename_coment_file_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
