# Generated by Django 5.2.7 on 2025-10-08 09:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0005_rename_user_file_owner_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='date_downloaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.IntegerField(default=544),
            preserve_default=False,
        ),
    ]
