# Generated by Django 5.2.7 on 2025-10-08 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0006_file_date_downloaded_file_date_uploaded_file_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='url',
            new_name='pub_url',
        ),
        migrations.RemoveField(
            model_name='file',
            name='unique_name',
        ),
    ]
