export const AUTH = '/auth/token/login'
export const ME = '/auth/users/me/'
export const FILES = '/cloud/files/'
export const STAFF_FILES_URL = '/cloud/files/filter/'
export const LOGOUT = '/auth/token/logout/'